### ISSUE TITLE
github認証を本番環境へ適用する

### ISSUE THREAD

**Issue by konjikicity** [running-23/pickable#47]
## 概要
github認証を本番環境で適用する

##  ToDo(仮)調査中....

- [ ] github認証用のトークンをもう一つ作成して本番環境と開発環境で使い分ける(パrailsに書いてました)
- [ ] credentials.yml.encを編集して取得した本番環境用のトークンを記述
- [ ] sorcery.rbで処理を開発環境と本番環境で分ける必要あり[参考](https://kemarii.com/blog/rails/rails-env-branch/) 
- [ ] herokuにmaster.keyを渡す [参考](https://qiita.com/du26/items/64d87d987652c4108ae6)

## 懸念点
本番環境でログインできるかの確認方法がわからないです.....
修正してデプロイして確認するしかないかも？

**Comment by konjikicity** [comment]
１. githubログインで使用するトークンを使い分ける
<img width="676" alt="8d9d39ba18355328e6454c2cb6e82f12" src="https://user-images.githubusercontent.com/82688205/161462011-13be5667-8f6c-41ca-b51e-8cae4a916200.png">
現在トークンの設定はこのような感じになっているが
Homepage URLと Authorzation callback URL の部分が本番環境ではURLが異なる為

<img width="694" alt="f1e8c8f7ef062b2dc7958b94cd713d07" src="https://user-images.githubusercontent.com/82688205/161462317-8416088b-d8f8-414f-a7d2-7f76d4225eb7.png">

上記のトークンを作成して本番環境のURLでもgithubの値が取得できるようにした。

**Comment by konjikicity** [comment]
2. Multi Environment Credentialsを使用して`production.yml.enc`, `production.key`を生成する
rails6までは秘匿情報を環境毎に管理したい場合はcredentials.yml.encに環境を明示して記述する必要があった

```
# credentials.yml.enc

development:
  github:
    key: ***
    secret: ***
    callback_url: ***

production:
  github:
    key: ***
    secret: ***
    callback_url:  ***

```

Rails6では秘匿情報を環境毎に管理することができる仕組みがサポートされているのでこちらを使用する
`rails credentials:edit --environment production`を実行することで
`production.enc.yml`と`production.key`が生成される。
こちらに本番環境の記述をする。

メリット
本番環境では勝手に秘匿情報の取得を`production.yml.enc`から取得してくれるので
sorcery.rbにて`Rails.application.credentials.dig`で取得している秘匿情報をif文等で書き分けなくてよくなる
→ 記述量の削減につながる

**Comment by konjikicity** [comment]
3. production.yml.encを編集してもう一つ作ったトークンの情報を記述
先ほど作成した`production.yml.enc`を編集
```
# production.yml.enc

github: 
  key: 本番環境のクライアントID
  secret: 本番環境のクライアントシークレット
  callback_url: 本番環境のコールバックURL

secret_key_base: 本番環境ではこちらが必要になるらしい、もともとあったcredentials.yml.encに記述があったのでコピー
```
本番環境では上記の情報がsorcery.rbの`Rails.application.credentials.dig`で参照される。
念の為` RAILS_ENV=production rails c `で本番環境用のコンソールを立ち上げられるので
値を確認すると値が変わっていることを確認した。

**Comment by konjikicity** [comment]
4. herokuにproduction.keyを登録する。

heroku config:set RAILS_MASTER_KEY=`cat config/credentials/production.key`
を実行してherokuの環境変数に設定する。

以上の処理でgithubログインが本番環境にできるはず
